pkg.env <- new.env(parent = emptyenv())

pkg.env$NA_invalid <- "NA::a"
pkg.env$NA_missing <- "NA::b"
pkg.env$all_NAs <- c(pkg.env$NA_invalid, pkg.env$NA_missing)

pkg.env$margin_separator <- ","
pkg.env$cat_start_label_separator <- ";"

pkg.env$missing <- "missing"

pkg.env$db_var_start_infix <- "::"

pkg.env$rec_to_copy <- "copy"

pkg.env$var_details_cat <- "cat"
pkg.env$var_details_cont <- "cont"

pkg.env$var_cat <- "Categorical"

pkg.env$node_name.pmml <- "PMML"
pkg.env$node_name.data_dict <- "DataDictionary"
pkg.env$node_name.trans_dict <- "TransformationDictionary"
pkg.env$node_name.data_field <- "DataField"
pkg.env$node_name.extension <- "Extension"
pkg.env$node_name.constant <- "Constant"
pkg.env$node_name.value <- "Value"
pkg.env$node_name.interval <- "Interval"
pkg.env$node_name.derived_field <- "DerivedField"
pkg.env$node_name.apply <- "Apply"
pkg.env$node_name.field_ref <- "FieldRef"
pkg.env$node_name.local_transformations <- "LocalTransformations"
pkg.env$node_name.define_function <- "DefineFunction"
pkg.env$node_name.table_locator <- "TableLocator"
pkg.env$node_name.taxonomy <- "Taxonomy"
pkg.env$node_name.inline_table <- "InlineTable"
pkg.env$node_name.row <- "row"
pkg.env$node_name.row_index <- "index"

pkg.env$node_namespace.pmml <- "http://www.dmg.org/PMML-4_4"

pkg.env$node_attr.pmml_version <- "4.4"
pkg.env$node_attr.name.var_start_label <- "variableStartLabel"
pkg.env$node_attr.name.label_long <- "labelLong"
pkg.env$node_attr.name.units <- "units"
pkg.env$node_attr.name.cat_label_long <- "catLabelLong"

pkg.env$node_attr.closure.closed <- "closedClosed"
pkg.env$node_attr.closure.leftOpen <- "openClosed"
pkg.env$node_attr.closure.open <- "openOpen"
pkg.env$node_attr.closure.rightOpen <- "closedOpen"

pkg.env$node_attr.missing.true <- "true"
pkg.env$node_attr.optype.categorical <- "categorical"
pkg.env$node_attr.optype.continuous <- "continuous"

pkg.env$node_attr.function.if <- "if"
pkg.env$node_attr.function.and <- "and"
pkg.env$node_attr.function.or <- "or"
pkg.env$node_attr.function.greater_than <- "greaterThan"
pkg.env$node_attr.function.less_than <- "lessThan"
pkg.env$node_attr.function.equals <- "equal"

pkg.env$node_attr.dataType.integer <- "integer"
pkg.env$node_attr.dataType.string <- "string"
pkg.env$node_attr.dataType.float <- "float"

pkg.env$node_attr.property.valid <- "valid"
pkg.env$node_attr.property.invalid <- "invalid"
pkg.env$node_attr.property.missing <- "missing"

pkg.env$node_attr.DefineFunction.name <- "name"

pkg.env$node_attr.FieldRef.field <- "field"

pkg.env$node_attr.Apply.function <- "function"

pkg.env$node_attr.Value.value <- "value"
pkg.env$node_attr.Value.displayValue <- "displayValue"
pkg.env$node_attr.Value.property <- "property"

pkg.env$node_attr.Extension.name <- "name"
pkg.env$node_attr.Extension.value <- "value"

pkg.env$node_attr.TableLocator.location <- "location"
pkg.env$node_attr.TableLocator.taxonomy <- "taxonomy"
pkg.env$node_attr.TableLocator.name <- "name"

pkg.env$node_attr.Taxonomy.name <- "name"

pkg.env$variable_details$columns.recFrom.elseValue <- "else"

pkg.env$ModelExportCSV.variables <- "variables"
pkg.env$ModelStepsCSV.filePath <- "filePath"
pkg.env$ModelExportCSV.variable_details <- "variable-details"
pkg.env$ModelExportCSV.model_steps <- "model-steps"
pkg.env$ModelStepsCSV.step <- "step"
pkg.env$ModelStepsCSV.fileType <- "fileType"
pkg.env$ModelInternal.file <- "file"
pkg.env$PMML.Node.Attributes.Value.xmlns <- "http://www.dmg.org/PMML-4_4"
pkg.env$PMML.Node.Attributes.Value.xsi <- "http://www.w3.org/2001/XMLSchema-instance"
pkg.env$PMML.Node.Attributes.Value.PMML.Version <- "4.4"
pkg.env$PMML.Node.Header <- "Header"
pkg.env$PMML.Node.Application <- "Application"
pkg.env$variables.Time <- "time"
pkg.env$argument.Variables <- "variable"
pkg.env$argument.recEnd <- "recEnd"
pkg.env$PMML.Node.DataDictionary <- "DataDictionary"
pkg.env$PMML.Node.DataField <- "DataField"
pkg.env$PMML.Node.Attributes.Value.optype.cont <- "continuous"
pkg.env$PMML.Node.Attributes.Value.dataType.float <- "float"
pkg.env$PMML.Node.Extension <- "Extension"
pkg.env$PMML.Extension.names.units <- 'units'
pkg.env$argument.Units <- "units"
pkg.env$PMML.Extension.names.variableStartLabel <- 'variableStartLabel'
pkg.env$PMML.Node.Interval <- "Interval"
pkg.env$argument.DatabaseStart <- "databaseStart"
pkg.env$PMML.Node.DerivedField <- "DerivedField"
pkg.env$PMML.Node.Attributes.Value.optype.cat <- "categorical"
pkg.env$PMML.Node.Apply <- "Apply"
pkg.env$PMML.Node.Attributes.Value.function.if <- "if"
pkg.env$PMML.Node.Attributes.Value.function.equal <- "equal"
pkg.env$PMML.Node.FieldRef <- "FieldRef"
pkg.env$PMML.Node.Constant <- "Constant"
pkg.env$PMML.Node.TransformationDictionary <- "TransformationDictionary"
pkg.env$PMML.Node.Attributes.Value.function.minus <- "-"
pkg.env$variables.splitValue <- ";"
pkg.env$PMML.Node.Array <- "Array"
pkg.env$PMML.Node.Attributes.Value.Type.float <- "float"
pkg.env$PMML.Node.Attributes.Value.function.rcs <- "rcs"
pkg.env$PMML.Node.Attributes.Value.function.multiplication <- "*"
pkg.env$PMML.Node.FactorList <- "FactorList"
pkg.env$PMML.Node.ParameterList <- "ParameterList"
pkg.env$PMML.Node.Parameter <- "Parameter"

pkg.env$PMML.Node.Attributes.Value.startVar <- "p0"
pkg.env$PMML.Node.Attributes.Value.label.Intercept <- "Intercept"
pkg.env$PMML.Node.ParamMatrix <- "ParamMatrix"
pkg.env$PMML.Node.PCell <- "PCell"
pkg.env$PMML.Node.CovariateList <- "CovariateList"
pkg.env$PMML.Node.PPMatrix <- "PPMatrix"
pkg.env$PMML.Node.Parameter <- "Parameter"
pkg.env$PMML.Node.Attributes.Value.Var.incrementVar <- "p"
pkg.env$PMML.Node.Predictor <- "Predictor"
pkg.env$PMML.Node.PPCell <- "PPCell"
pkg.env$PMML.Node.Attributes.Value.Var.incrementVar <- "p"
pkg.env$PMML.Node.MiningSchema <- "MiningSchema"
pkg.env$PMML.Node.MiningField <- "MiningField"
pkg.env$PMML.Node.Attributes.Value.usageType.target <- "target"
pkg.env$PMML.Node.Attributes.Value.usageType.active <- "active"
pkg.env$PMML.Node.GeneralRegressionModel <- "GeneralRegressionModel"
pkg.env$PMML.Node.Attributes.Value.modelType.CoxRegression <- "CoxRegression"
pkg.env$PMML.Node.Attributes.Value.modelFunction.regression <- "regression"
pkg.env$PMML.Node.BaseCumHazardTables <- "BaseCumHazardTables"
pkg.env$PMML.Node.BaselineCell <- "BaselineCell"
pkg.env$simple_model_name_column <- "name"
pkg.env$PMML.OutputNode <- "Output"
pkg.env$PMML.OutputFieldNode <- "OutputField"
pkg.env$PMML.Node.Attributes.Value.dataType.string <- "string"
pkg.env$PMML.Node.NumericPredictor <- "NumericPredictor"
pkg.env$PMML.Node.RegressionTable <- "RegressionTable"
pkg.env$PMML.Node.RegressionModel <- "RegressionModel"
pkg.env$PMML.regression_function_name <- "regression"
pkg.env$PMML.softmax_normalization_method <- "softmax"

pkg.env$PMML.OutputFieldNode.attrs.name <- "name"
pkg.env$PMML.SimpleModelNode <- "SimpleModel"

pkg.env$simple_model_output_variable_entry <- "outputVariableName"
pkg.env$simple_model_value_column <- "value"

pkg.env$columns.Variable <- "variable"
pkg.env$columns.DatabaseStart <- "databaseStart"
pkg.env$columns.VariableStart <- "variableStart"
pkg.env$columns.recTo <- "recEnd"
pkg.env$columns.recFrom <- "recStart"
pkg.env$columns.variablesDetails.typeStart <- "typeStart"

pkg.env$recode.key.tables <- "tables::"

pkg.env$logistic_regression_step <- "logistic-regression"
pkg.env$logistic_regression_yes_target_category <- "yes"
pkg.env$logistic_regression_no_target_category <- "no"
pkg.env$logistic_regression_zero_intercept <- "0"

pkg.env$intercept_coefficient <- "Intercept"
